- sigopt/exception.py
> Add str/repr methods to ApiException

- sigopt/v1/interface.py
Single cohort:
POST /experiment/<eid>/cohorts
GET /experiment/<eid>/cohorts/<cid>
PUT /experiment/<eid>/cohorts/<cid>
Paginated multiple cohorts:
GET /experiment/<eid>/cohorts
> Add v1 cohort endpoints

- sigopt/objects.py
> Add timestamp

- sigopt/objects.py
Add a created field to Experiments, Observations, Suggestions and Clients
> created fields on v1 objects

- sigopt/objects.py
> accidentally added created to wrong object

- .travis.yml
- README.md
- requirements.txt
- setup.py
- sigopt/compat.py
- sigopt/exception.py
- sigopt/interface.py
- sigopt/objects.py
- sigopt/requestor.py
- sigopt/resource.py
- test/test_endpoint.py
- test/test_object.py
- test/test_requestor.py
And then fix some issues that arose from those tests
@alexandraj777
> Add some tests

- sigopt/objects.py
> Clean up API Object fields

- .gitignore
- examples/parallel.py
Couple comments and change domain.  Not as short as the EggHolder
function, but still okay.  @alexandraj777
> Convert test from EggHolder to Franke

- sigopt/compat.py
- sigopt/interface.py
- sigopt/resource.py
> Some linting

- publish
- sigopt/version.py
> Bump version

- requirements.txt
- setup.py
> More generous requirements

- sigopt/interface.py
> Expose public method for setting API url

- sigopt/interface.py
- sigopt/objects.py
- test/test_endpoint.py
- test/test_object.py
> /v1/clients/X/plan

- sigopt/exception.py
- sigopt/interface.py
- sigopt/requestor.py
- test/test_requestor.py
> More granular exception types

- sigopt/objects.py
- sigopt/version.py
User provided names should be unicode
> When names contain emoji str(name) breaks

- sigopt/interface.py
- sigopt/objects.py
- test/test_object.py
> Make Assignments and Metadata more dict-like

- sigopt/objects.py
- test/test_object.py
> Deprecate some fields

- sigopt/interface.py
- sigopt/requestor.py
- test/test_endpoint.py
- test/test_interface.py
- test/test_requestor.py
> Split Connection interface from impl

- sigopt/requestor.py
> Fix requestor construction

- .travis.yml
- lint
- sigopt/exception.py
- sigopt/objects.py
> Some lint fixes

- sigopt/endpoint.py
- sigopt/interface.py
- sigopt/objects.py
- test/test_object.py
- test/test_pagination.py
> Iterate over pages in python library

- README.md
- examples/basic.py
- examples/other_languages.py
- examples/parallel.py
- sigopt/__init__.py
> Expose sigopt.Connection

- sigopt/objects.py
@alexandraj777
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/sigopt/sigopt-python/57)
> Use six.text_type throughout

- examples/parallel.py
- setup.py
- sigopt/examples/__init__.py
- sigopt/examples/franke.py
To make some examples cleaner
@chrix-sigopt
> Add franke function to python library

- examples/basic.py
- sigopt/objects.py
- sigopt/version.py
> Add observation budget

- .travis.yml
- Makefile
- lint
- requirements-dev.txt
Let's see how this does with Travis!
> Makefile, and dev requirements

- sigopt/endpoint.py
- sigopt/interface.py
- sigopt/objects.py
- sigopt/version.py
- test/test_requestor.py
> Fix return type of delete endpoints

- sigopt/objects.py
> Add missing fold field

- sigopt/objects.py
- test/test_object.py
> Prefer best_assignments enpdoint

- sigopt/objects.py
- test/test_object.py
> Multicriteria

- setup.py
- sigopt/endpoint.py
- sigopt/exception.py
- sigopt/objects.py
- sigopt/resource.py
- test/test_endpoint.py
- test/test_resource.py
> Expose some more functions for matlab client

- sigopt/interface.py
- sigopt/objects.py
- sigopt/version.py
@pfhayes 
For use after https://github.com/sigopt/sigopt-api/pull/2073 is
accepted.
> Add a stopping criteria resource

- test/test_object.py
> Add tests for conditionals

- sigopt/objects.py
- test/test_object.py
> Add constraints

- MANIFEST.in
- setup.py
> Add MANIFEST so LICENSE is included

- sigopt/requestor.py
Allows reusing TCP connections
@alexandraj777
> Use requests sessions

- sigopt/interface.py
- test/test_interface.py
> Support SIGOPT_API_URL in env

- .travis.yml
- README.md
- examples/basic.py
- examples/other_languages.py
- examples/parallel.py
Should only me merged AFTER org-v1 goes into prod
> Update user profile refs to token info

- sigopt/interface.py
- sigopt/objects.py
- test/test_object.py
> Add importances to python client

- sigopt/interface.py
- sigopt/objects.py
- test/test_endpoint.py
- test/test_object.py
Allows site admins to `GET` information about organizations.
> Add organizations GET

- sigopt/objects.py
- test/test_object.py
This will allow customers to access task information.  Will need to wait for requisite merger on API side.
> Parse task info from API

- .travis.yml
- Makefile
`make update` will make it easier for developers to get started in a fresh venv
> make update command

- .travis.yml
Was seeing this error https://github.com/PyCQA/astroid/issues/649 which seems to have been fixed in v2.3.0
> upgrade pylint to 2.3.0

- examples/basic.py
- examples/parallel.py
> sigopt-examples project in experiment create

- test/test_pagination.py
Adds another xfail to be fixed in next major version bump
> Updates to pagination tests

- sigopt/objects.py
- test/json/experiment.json
- test/json/metric.json
- test/test_object.py
This PR adds `objective` to the metric object.
> Metric Minimization: Add objective

- sigopt/version.py
- metric thresholds
- metric minimization
> bump version to 4.2.0

- sigopt/objects.py
- test/json/experiment.json
- test/json/metric.json
- test/test_object.py
Should wait until we actually enable the feature, but technically already works.
> Metric strategy field

- Makefile
seems to be the original intent
> fix the makefile

- .circleci/config.yml
This is the newest major release.
> Support python 3.8

- sigopt/interface.py
Exposed some non-existent endpoints
> Fix token scope

- sigopt/lib.py
- sigopt/objects.py
- sigopt/version.py
- test/test_lib.py
- test/test_object.py
- test/test_pagination.py
- test/utils.py
- Warning when users access `data` directly, to let them know they
may be missing data.
- Update and test Pagination repr
> Updates to Pagination object

- sigopt/lib.py
- sigopt/objects.py
- sigopt/version.py
- test/test_lib.py
- test/test_object.py
- test/test_pagination.py
- test/utils.py
Ensure every wunexpected warning is a failure,
consolidate warning checking
> More diligent testing of warnings

- .circleci/config.yml
- requirements-dev.txt
- test/cli/test_files/warning_sigopt.yml
- test/cli/test_optimize.py
One test started failing when we updated pytest, not exactly clear why. But it was testing two things so I just split those out
> Test sigopt-python on Python 3.9

- sigopt/cli/utils.py
`import git` raises `ImportError` if `git` (cli) isn't installed -_-
> dont need git

- sigopt/__init__.py
- sigopt/cli/utils.py
- sigopt/runs/context.py
https://app.asana.com/0/1199993631890968/1200025066763643/f
> sigopt.get_run_id()

- sigopt/version.py
- Add support for the `transformation` field on `parameter` objects
- Add support for `get_run_id` exposure
> version 7.4.0

- sigopt/cli/arguments/__init__.py
- sigopt/cli/arguments/experiment_id.py
- sigopt/cli/commands/__init__.py
- sigopt/cli/commands/experiment/__init__.py
- sigopt/cli/commands/experiment/base.py
- sigopt/cli/commands/experiment/create.py
- sigopt/cli/commands/experiment/start_worker.py
- sigopt/cli/commands/local/__init__.py
- sigopt/cli/commands/local/optimize.py
- sigopt/cli/commands/local/run.py
- sigopt/cli/commands/local/start_worker.py
- sigopt/cli/utils.py
- sigopt/factory.py
- test/cli/test_optimize.py
- test/cli/test_run.py
```
sigopt experiment create [-e experiment.yml]
sigopt start-worker EXPERIMENT_ID
```
> Commands for parallel experimentation with the CLI

- sigopt/run_context.py
- test/cli/test_truncate.py
Into sj/main or shoudl we release this now?
> reduce log limit

- sigopt/objects.py
We hadn't added this with grid experiments it seems.
> add grid to parameter

- sigopt/cli/arguments/__init__.py
- sigopt/cli/arguments/source_file.py
- sigopt/cli/commands/config.py
- sigopt/cli/commands/local/optimize.py
- sigopt/cli/commands/local/run.py
- sigopt/cli/utils.py
- sigopt/config.py
- sigopt/magics.py
- test/cli/test_cli_config.py
- test/cli/test_optimize.py
- test/cli/test_run.py
Users can opt into uploading source code with a CLI argument that specifies the code file to track.
> Source file CLI option

- controller/Dockerfile
alpine-snyk-finding
no idea what it is / where it gets used, but, this makes snyk happy
> alpine-snyk-finding

- sigopt/experiment_context.py
```python
experiment = sigopt.get_experiment("123")
experiment.archive()
assert experiment.state == "deleted"
```
> Archive experiment

- sigopt/__init__.py
- sigopt/factory.py
- test/test_set_project.py
set the global project id for creating runs and experiments without the CLI
> sigopt.set_project

- sigopt/factory.py
- sigopt/validate/experiment_input.py
- sigopt/validate/keys.py
Enables differentiation in the UI
> runs_only passed to experiment create

- test/runs/test_utils.py
got flagged for not properly closing resources
> pil image with

- sigopt/log_capture.py
- sigopt/objects.py
These should be clean enough; there's a few other cases but they're more on customer-facing calls so I wanna think more before we break a potential kwarg
> dont redefine builtins

- sigopt/cli/arguments/__init__.py
- sigopt/cli/arguments/project.py
- sigopt/cli/commands/cluster/optimize.py
- sigopt/cli/commands/cluster/run.py
- sigopt/cli/commands/cluster/test_run.py
- sigopt/cli/commands/local/optimize.py
- sigopt/cli/commands/local/run.py
- sigopt/cli/utils.py
- sigopt/orchestrate/controller.py
- sigopt/orchestrate/job_runner/service.py
- sigopt/orchestrate/sigopt/service.py
- test/cli/test_cluster_kubectl.py
- test/cli/test_run.py
```bash
sigopt run --project=X
sigopt optimize --project=X
sigopt cluster run --project=X
sigopt cluster test-run --project=X
sigopt cluster optimize --project=X
```
> Project option for CLI

- controller/controller/missing_pods.py
- sigopt/experiment_context.py
- sigopt/objects.py
- sigopt/orchestrate/job_status/service.py
- sigopt/orchestrate/status.py
- sigopt/validate/experiment_input.py
- test/orchestrate/job_status/service_test.py
- test/validate/test_validate_experiment.py
observation_budget => budget
observation_budget_consumed => total_run_count, remaining_budget
> Update budget and progress

- sigopt/lib.py
- sigopt/magics.py
- sigopt/runs/context.py
Try to fix the api url in messages.
> fix api_url is output messages

- LICENSES/third_party/third-party-licenses.txt
TPP file we can link in Docker README once merged / readily available.
> tpp licenses

- sigopt/__init__.py
- sigopt/cli/arguments/__init__.py
- sigopt/cli/arguments/experiment_id.py
- sigopt/cli/arguments/validate.py
- sigopt/cli/commands/__init__.py
- sigopt/cli/commands/base.py
- sigopt/cli/commands/experiment/__init__.py
- sigopt/cli/commands/experiment/archive.py
- sigopt/cli/commands/experiment/base.py
- sigopt/cli/commands/experiment/create.py
- sigopt/cli/commands/experiment/unarchive.py
- sigopt/cli/commands/training_run/__init__.py
- sigopt/cli/commands/training_run/archive.py
- sigopt/cli/commands/training_run/base.py
- sigopt/cli/commands/training_run/unarchive.py
- sigopt/factory.py
- sigopt/interface.py
https://sigoptintel.atlassian.net/browse/SN-208
> Add archive and unarchive commands for Run and Experiment

- .gitignore
- sigopt/xgboost/run.py
No longer logging eval_metric as param.
> Fix eval_metric logging

- sigopt/xgboost/run.py
Give user the ability specify the name of a run.
Requested by Eddie
> Allow user specifying run-name

- integration_test/test_xgboost.py
- sigopt/xgboost/compute_metrics.py
- sigopt/xgboost/run.py
- test/xgboost/test_compute_metric.py
* Add unit test for metric computation
* Update integration test coverage
> New integration test 

- integration_test/test_xgboost.py
All I'm doing is pulling out the _form_random_run_params function in TestXGBoost (and adding an __init__.py) so I can import it for the XGB experiment integration test
> pull out _form_random_run_params, add __init__.py for importing

- sigopt/run_context.py
> Parameters meta / Parameter Source

- integration_test/test_xgboost_run.py
- sigopt/xgboost/checkpoint_callback.py
- sigopt/xgboost/run.py
- test/xgboost/test_run_options_parsing.py
Also rearrange the order of operation to let xgb.train do some of the error handling for us.
> Expand the run API to accept all xgb.train parameter

- integration_test/test_xgboost_run.py
Gotta supply all the param values for this test.
> patch up integration test

- requirements.txt
- setup.py
- sigopt/compat.py
- sigopt/xgboost/checkpoint_callback.py
- sigopt/xgboost/compat.py
- sigopt/xgboost/compute_metrics.py
- sigopt/xgboost/run.py
Check import xgboost and version?
> graceful import

- integration_test/test_xgboost_experiment.py
- integration_test/test_xgboost_run.py
- sigopt/xgboost/constants.py
- sigopt/xgboost/experiment.py
- sigopt/xgboost/run.py
- sigopt/xgboost/utils.py
- test/xgboost/test_experiment_config.py
Can change the source name to something other than `User Specified`.
> log param source

- integration_test/test_xgboost_run.py
- sigopt/xgboost/run.py
- test/xgboost/test_run_options_parsing.py
Based on gustavo's feedback. Can revert if we get more conflicting feedbacks.
> log_* -> autolog_*

- integration_test/test_xgboost_run.py
- sigopt/xgboost/run.py
My bad, was not passing the correct num_boost_round when running experiment.
Added a test to verify it's working appropriately now.
> mistake with threading num_boost_round

- sigopt/xgboost/run.py
- test/xgboost/test_run_options_parsing.py
> Check type for run_options entries.

- integration_test/test_xgboost_run.py
- sigopt/xgboost/constants.py
- sigopt/xgboost/run.py
I feel like all the training set metrics are cluttering up the web.
> Proposal: Remove training set metrics

- examples/basic.py
- examples/parallel.py
Update the examples to use training runs, based on the guidance in the docs. 
These are closer to the docs but not really runnable, but then again the previous stuff wasn't either.
> Switch to using 8.0.0 API for examples

- .circleci/config.yml
- ci/tutorial/model.py
- ci/tutorial/sigopt_config.exp
This automates the run tutorial and runs it as part of rot-check, to emulate first run user experience.
> Add tutorial test

- sigopt/version.py
Changelog:
* Hyperopt integration
* Improved CLI command descriptions
* Configure SigOpt in a Jupyter notebook
* Update experiment parameters with experiment.update()
* Handle rate-limiting errors automatically
* Enable keep-alive sessions to reduce API overhead
> v8.3.0 release

- sigopt/version.py
Changelog:
* Xgboost early stopping by @ericlee0803
> 8.4.0 release

- sigopt/version.py
* Use new AI Experiment endpoints
* Add AI Experiment functions: `create_aiexperiment`, `archive_aiexperiment`, `unarchive_aiexperiment`
> Version 8.6.0

- tools/check_copyright_and_license_disclaimers.py
Can turn into a CI check by running `check_all()`; can turn into a pre-commit linter/fixer by adding in `--fix-in-place` flag.
Currently applies to python and Dockerfile; can expand over time if needed.
> Copyright and license disclaimers

- integration_test/test_xgboost_run.py
should fix broken integration test
> remove unnecessary kwargs key from TestFormCallbacks

- README.md
- examples/README.md
- sigopt/objects.py
- sigopt/orchestrate/aws/service.py
- sigopt/orchestrate/exceptions.py
- sigopt/run_context.py
- sigopt/xgboost/run.py
Update doc link.
Clean up nested if statements a bit.
> More cleanup

- .circleci/config.yml
- .github/workflows/tests.yml
TODO (future work): migrate tutorial test. Maybe we can check out the latest version of `sigopt-server` and test against that.
> Github actions

- .github/workflows/integration.yml
> stop downgrading docker

- .github/workflows/integration.yml
- .github/workflows/tests.yml
Add permissions to workflows for security purposes.
> Add workflow permissions

- .github/workflows/integration.yml
- .github/workflows/tests.yml
- integration_test/test_xgboost_run.py
- requirements-dev.txt
- sigopt/xgboost/run.py
- test/xgboost/test_run_options_parsing.py
This bumps some XGBoost stuff and deals with things that changed underneath us. There will be a separate PR to make this work with py3.12, which removed distutils so we'll have to change how the packaging works.
> Work on GitHub actions

- .github/workflows/tests.yml
- requirements-dev.txt
- setup.py
- test/runs/test_set_project.py
> Bump to add 3.12

- .github/workflows/scorecard.yml
Nodejs 16 is deprecated, bump the versions
> Bump nodejs in scorecard

- MANIFEST.in
Adresses https://github.com/sigopt/sigopt-python/issues/439
> Add requirements.txt to source manifest

- .github/auto_assign-issues.yml
- CODEOWNERS
Switch to team based for user alerting.
> Switch to team based codeownership
