sigopt/sigopt-python

sigopt/v1/interface.py
Some clients may strip body of delete request, url params is a safer way to pass params.
In addition, resource identified by GET uri may be deleted with DELETE uri (if implemented)
=> DELETE's params should follow GET

sigopt/resource.py
Dancing a little bit between helpful error for v1 or for v0. If conn is a `v1` connection, these are possible error messages the user could see if they misspell, or are attempting to request a `v0` endpoint.
```
conn.experiments(1715).fetc()
AttributeError: Cannot find attribute `fetc` on resource `experiments`, likely no endpoint exists for: https://api.sigopt.com/v1/experiments/1715/fetc, or `experiments` does not support `fetc`.
```
```
conn.experiments(1715).history()
AttributeError: Cannot find attribute `history` on resource `experiments`, likely no endpoint exists for: https://api.sigopt.com/v1/experiments/1715/history, or `experiments` does not support `history`.
```
=> More helpful error message for attribute-error

sigopt/resource.py
Example:
```
experiment_id = 1
conn.experiments(experiment_id).fetch()
```
This will call `/v1/experiments/1`
If however, `experiment_id` is accidentally `None`, then the call
will be
```
/v1/experiments
```
which has a completely different format which will cause subtle
errors. With this change, the call will be
```
/v1/experiments/None
```
which is not a real endpoint, but the error is more apparent.
I think this is the right behaviour since it's unlikely that someone
will actually want to switch programmatically between
`conn.experiments(1)` and `conn.experiments()`
@alexandraj777
=> Default to a signal value instead of None

sigopt/interface.py, sigopt/version.py
cc @pfhayes Allow custom user agents, useful for things like scikit-learn integration. Always tag the sigopt-python version in headers.
=> allow changing the user_agent header

.travis.yml
Reached EOL, not supported by travis
@alexandraj777
=> Remove support for Python 2.6

sigopt/objects.py
There is no `reference_id` endpoint.
=> Fix reference_id deprecation warning

sigopt/objects.py
This field is not in the docs anymore. By request from @startakovsky.
=> Deprecate metric field in the Experiment object

.gitignore, sigopt/objects.py, test/test_interface.py, test/test_object.py
added `updated` and `user` fields to `experiment` object, as requested on [asana ticket](https://app.asana.com/0/160711400613812/555133661704417).
Noticed a few other things; I can break into separate PRs if desired.
=> expose experiment fields

sigopt/interface.py, sigopt/requestor.py, test/test_interface.py
Add configurable HTTP timeout for a `Connection`. Setting the timeout would look something like: `conn.set_timeout(5)`
=> Configurable HTTP Timeout

setup.py
Can occur when you are installing via pip in a fresh virtualenv
```
$ pip install -e ".[dev]"
Obtaining file:///Users/patrick/dev/sigopt-python
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/Users/patrick/dev/sigopt-python/setup.py", line 5, in <module>
from sigopt.version import VERSION
File "/Users/patrick/dev/sigopt-python/sigopt/__init__.py", line 1, in <module>
from .interface import Connection
File "/Users/patrick/dev/sigopt-python/sigopt/interface.py", line 20, in <module>
from .requestor import Requestor, DEFAULT_API_URL
File "/Users/patrick/dev/sigopt-python/sigopt/requestor.py", line 1, in <module>
import requests
ModuleNotFoundError: No module named 'requests'
```
@alexandraj777
=> Fix install on platforms without `requests`

sigopt/requestor.py
https://github.com/requests/requests/issues/4664 gives a good explanation of the problem:
> If python sends a request at roughly the same time as the server closes the
session, then the server will send a RST (as the session is closed). Python
receives this RST on what it thought was a valid session and throws an
error
This can be handled by setting `max_retries` in the `requests.adapters.HTTPAdapter` class (the requests default is 0) which will retry on a `ConnectionError`.
=> Max retries for Requestor object

sigopt/lib.py
Was testing out the python client in a fresh venv and this `six` reference was failing. Not sure why this wasn't caught by travis?
=> missing six import

sigopt/requestor.py
We don't have a stateful API so `requests.Session` is not really required. We use it for keep-alive but this has been causing us issues.
This change should eliminate the chance for a protocol error caused by a `RST` packet from a load balancer (unless a request really is taking longer then 30s).
=> Remove session from requestor

sigopt/objects.py, test/test_object.py
Will rebase after merging #130 
After observing dozens of engineers use our API client in ipython notebooks, it's clear that our object serialization causes users to think that field access on objects like `Experiment` and `Metric` is done via square brackets. The goal of this PR is to change the serialization of the appropriate API objects so that users are nudged as to when they should use dot notation to access a field, and when they should use square brackets.
At the end of this description, I've included an example of the dramatic difference between in the `Experiment` object. Note how it's much cognitively easier to interpret the types of all of the sub-objects nested into the `Experiment`, both because of capitalization of object names, but also the `=` vs the `:` separators. Also …
=> Serialize objects

sigopt/interface.py, sigopt/objects.py
Adds projects as a subresource of clients and updates the client-side experiment object.
```python
conn.clients(client_id).projects().fetch().iterate_pages()
conn.clients(client_id).projects().create(**kwargs)
conn.clients(client_id).projects(project_id).fetch()
conn.clients(client_id).projects(project_id).update(**kwargs)
conn.clients(client_id).projects(project_id).experiments().fetch().iterate_pages()
conn.clients(client_id).experiments(experiment_id).project
```
@benhsu75
=> Add Projects

sigopt/interface.py, sigopt/objects.py, sigopt/requestor.py
Enables a few separate but related pieces:
- ~`ca_bundle`: useful if sigopt is run with SSL certs not recognized by default~
- `client_ssl_certs`: useful if client authentication is done via SSL / PKI, rather than username/password
- `pki_sessions()` for lower-level connecting
- ~`pki_login()` convenience function for navigating a full PKI connection~
=> Client certificates

sigopt/objects.py
A little rough in that every `Prior` object will have all fields, but some will be `None`; looks like we don't (yet) have a `OneOf()` for this type of behavior.
=> parameter priors

sigopt/objects.py
- Prevents DeprecationWarnings from being omitted on calls to repr
- Also discourages their use
=> Exclude deprecated fields from repr

sigopt/run_params.py
Support `sigopt.params.setdefaults({"p1": 1})` and `sigopt.params.setdefaults(p1=1)`. Same function signature and similar functionality to `dict.update`.
=> params.setdefaults

sigopt/__init__.py, sigopt/run_context.py
This method makes it easier to log multiple metrics at once.
examples:
```python
sigopt.log_metrics({"m1": 5, "m2": 1})
sigopt.log_metrics(m1=5, m2=1)
```
=> log_metrics method

sigopt/cli/utils.py
KeyboardInterrupt sometimes causes a subsequent `ProcessLookupError` when the user's program exits quickly
=> fix missing process

sigopt/run_context.py, sigopt/run_params.py
=> use global_run_context.params if run.assignments is empty

sigopt/experiment_context.py
I would consider it a bug that the experiment's training runs list endpoint does not return all attributes (because it was made for training monitor) but this is the minimal change to fix
=> use the project runs endpoint to fetch runs

sigopt/ratelimit.py, sigopt/requestor.py
- implement some small client-side backoff for users who accidentally make malformed calls in a tight loop
- `time-based rate-limiting`: users are allowed 30 requests per second
- `failed-status rate-limiting`: if calls are continually failing, they shouldn't continue to come at a rapid pace
Pretty straightforward - take a timestamp at second-level granularity, and once they reach the limit, we sleep for 1-2 seconds.
Shortcomings:
- process (thread?) specific, so multiple processes / multiple machines won't get blocked as quickly
Also straightforward - keep a running count of consecutive failed (`not (200 <= status <= 299)`) requests. Users are allowed 5 before we enforce a 1-2 second sleep. Resets on any successful request.
Benefits:
- while it doesn't share token-based failures with …
=> client-side rate-limit

sigopt/xgboost/compute_metrics.py
fix issue where sometimes classification predictions are vector-valued instead of integers. 
Checked with multi:softmax and multi:softprob objectives and worked okay.
=> quick fix for compute_metrics

integration_test/test_xgboost_experiment.py
Preventing triggering the internal SoftException PD.
cc @dwanderson-intel
=> At least 1 double parameter in experiment integration test

integration_test/test_xgboost_run.py, sigopt/xgboost/run.py, sigopt/xgboost/utils.py
Simplifying some of log default parameters logic.
* Always log `num_boost_round` as user specified.
* Remove option to set `log_params` in run_options.
* Add option `log_xgboost_defaults` to turn on/off xgboost default logging.
=> Simplifying xgboost defaults

integration_test/test_xgboost_experiment.py, sigopt/xgboost/experiment.py, sigopt/xgboost/run.py
@ericlee0803 , I rearranged how the params are being passed around if `sigopt.xgboost.run` is created with a `run`. 
Now, it is more explicit that at the `train_model` stage, we need to merge all the params together, instead of before where I did it at the `create_run` stage.
Let me know if you think this makes more sense.
=> params overwriting

integration_test/test_xgboost_run.py, sigopt/context.py, sigopt/model_aware_run.py, sigopt/xgboost/run.py
Renaming Context -> ModelAwareRun, then we we can create `XGBRun`, `LGBMRun`, inheriting from `XGBRun`.
We would have to rename anyway, since there is already a Context class under in `sigopt/cli/commands/cluster/base.py`.
=> Proposal: Renaming Context to something more understandable.

sigopt/interface.py, sigopt/urllib3_patch.py, test/test_interface.py, test/test_urllib3_patch.py
This had previously been removed because the load balancer could send a RST packet while the client was closing the connection.
Our LBs don't send a `Keep-Alive` header to specify a timeout and it appears that cloudflare's proxy doesn't send this information either. In any event, `urllib3` and `requests` don't care and will leave a session open until the socket is closed via RST packet, which could happen simultaneously with a non-idempotent request.
This PR includes a patch to urllib3's classes to not keep a connection idle for more than 30s, which is at least lower than the idle timeout of our AWS LB.
See https://github.com/sigopt/sigopt-python/pull/122 for past performance, although note that that testing was done in the SF office and my testing today was done from NY.
**no keepalive** …
=> Revive keepalive

sigopt/requestor.py
Tested with a stress test script, previously observed a bunch of 429 errors and now the script chuggs away without issue.
=> Exponential backoff on rate limited requests

sigopt/factory.py
Allow runs to be archived when experiments are archived via the python client.
=> Add include_runs parameter to archive_experiment

sigopt/cli/commands/experiment/archive.py, sigopt/cli/commands/experiment/unarchive.py, sigopt/cli/commands/local/run.py, sigopt/cli/commands/local/start_worker.py, sigopt/cli/commands/training_run/archive.py, sigopt/cli/commands/training_run/unarchive.py, sigopt/defaults.py, sigopt/exception.py, sigopt/factory.py, test/runs/test_factory.py
Putting training runs in the wrong projects seems to be a common issue. It can be caused by inferring the project ID from the name of the current directory and automatically creating a project with that ID. By removing the auto project creation the user must choose to create a new project or set the `SIGOPT_PROJECT` variable/rename the directory.
=> Don't auto create projects

sigopt/__init__.py, sigopt/cli/arguments/__init__.py, sigopt/cli/arguments/project.py, sigopt/cli/commands/__init__.py, sigopt/cli/commands/project/__init__.py, sigopt/cli/commands/project/create.py, sigopt/defaults.py, sigopt/exception.py, sigopt/factory.py
```
Usage: sigopt create project [OPTIONS]
Create a SigOpt Project.
Options:
-p, --project TEXT   Provide the project ID. Projects can be created at
https://app.sigopt.com/projects or with the command
`sigopt create project`. If a project ID is not
provided then the project ID is determined in the
following order: first from the SIGOPT_PROJECT
environment variable, then by the name of the current
directory.
--project-name TEXT  The name of the project.
--help               Show this message and exit.
```
```python
import sigopt
sigopt.create_project("optional-project-id", "Optional Project Name")
```
=> Create projects via the CLI and client

sigopt/version.py
- use `aiexperiment` URLs where appropriate
- copyright, license, inclusive language improvements
=> Version 8.6.1

sigopt/xgboost/experiment.py, sigopt/xgboost/run.py, test/xgboost/test_run_options_parsing.py
Some patches for xgboost integration based on recent feedback.
* Missing f-strings
* Skip uploading feature importances if feature_name has > 100 chars
* Using `**kwargs` to handle `xgboost.train` arguments that are not integrated to SigOpt. I think this will also allow us to support future versions of xgb (version > 1.5.x).
=> Patches for XGB integration

setup.py
Now that we are passing non-integrated arguments via `**kwargs`, we could unpin the max version of XGBoost.
=> Unpin max version of xgboost

requirements.txt
Hopefully helps users resolve this [issue](https://github.com/yaml/pyyaml/issues/601) by allowing them to pin PyYAML <= 5.3.1 or >= 6.0. The way we pinned >=5.4.1,<6 forces 5.4.1 to be installed which is not compatible with cython<3.0 in a way that is opaque to pip.
=> Lax pin on PyYAML
